services/main.tf, services/variables.tf
If the caller doesn't supply an explicit path pattern, we add `/management/healthcheck` to their ALB path pattern and use that instead. One less line to write in the caller config.
=> Set a default healthcheck path based on path pattern

ecs_script_task/cloudwatch.tf, ecs_script_task/variables.tf, services/ecs_tasks/cloudwatch.tf, services/ecs_tasks/variables.tf, services/variables.tf, userdata/cloudwatch.tf, userdata/variables.tf
Don't enforce `platform` prefix on Cloudwatch log group names.
=> Make log_group_name_prefix variable

ecr/repository.tf, ecr/variables.tf
In order to make that module more reusable.
=> Remove uk.ac.wellcome namespace from ECR repo

service/variables.tf
The docs here are wrong.
I wasn't sure why this was the default (quite hard to figure out) - but at least now the docs reflect it.
=> healthcheck_path default docs to reflect the truth

service/ecs_task/data.tf, service/ecs_task/variables.tf, service/main.tf, service/variables.tf, sqs_autoscaling_service/main.tf, sqs_autoscaling_service/variables.tf
This works around a weirdness in Terraform’s interpolation abilities. Yes, it sucks, but it seems to work in the sierra_adapter stack, and I don’t want to fiddle any more with this.
=> Make the environment variables length a static variable

autoscaling/app/ecs/main.tf, sqs_autoscaling_service/main.tf
This is tested and applied in the Sierra stack; it stops our autoscaling targets being continually recreated.
=> Terrible fix for the autoscaling whack-a-mole

RELEASE.md, ecs/service/ecs_service/ecs.tf
This represents a major change in the way we do services, but I think it’s justified.
* Our public-facing services (API and Loris) have a statically defined size. This means we can define their size entirely in Terraform, and it will actually update!
* Most of our pipeline services (ingestor, ID minter, adapters) are queue-backed, and use our autoscaling modules. If the size of one of these services is temporarily reduced to zero, autoscaling quickly picks it back up again.
* The reindexer is the one problem here, but since reindexes are (relatively) rare, I think it’s better to push this weirdness out of Terraform and rely on us spotting when we’ve accidentally stopped the reindexer mid-reindex. (Note: this is much easier than fixing …
=> Don't ignore the desired count on services

.travis.yml, Makefile, RELEASE.md, _scripts/hypothesistooling.py, _scripts/run_travis_format.py, ecs/service/ecs_service/alarms.tf
Specifically, don't fire when you're scaling a deployment!
=> Make the ALB alarms a bit less chatty

ecs/cluster/asg/ecs_asg_launch_config/variables.tf, ecs/cluster/asg/variables.tf, ecs/cluster/variables.tf
In order that multiple different subnets can SSH to instances.
=> Allow admin_cidr_ingress to be a list of CIDR blocks

efs/README.md, efs/main.tf, efs/variables.tf
Changing variable to allow a list of security groups to be used in the
ingress rules for the EFS mount targets.
This can then be used by the ECS/cluster module with its on demand and spot instances SGs.
=> EFS: allow access to EFS mount targets from list of security groups

ecs/cluster/userdata.tf, ecs/cluster/variables.tf
To allow for an ECS cluster with an EFS mounted, the variable efs_filesystem_id is introduced in the ecs/cluster module and passed on to the userdata module (default value is the same in both modules).
=> add variable efs_filesystem_id to pass it on to userdata module

RELEASE.md, autoscaling/alarms/sqs/main.tf
I've seen weird behaviour in the sqs autoscaling where both the scale down and scale up alarms are triggered and that makes the autoscaling go up and down. _I think_ this is due to the fact that we that missing data as breaching for the scale down alarm which makes it possible for both alarms to be triggered at the same time. 
I've set it to ignore for the elasticdump and it seems to be behaving better
=> Ignore missing data to avoid autoscaling being triggered up and down

RELEASE.md, autoscaling/alarms/cpureservation/cpureservation_alarm/main.tf, autoscaling/alarms/cpureservation/cpureservation_alarm/variables.tf, autoscaling/alarms/cpureservation/main.tf, autoscaling/alarms/cpureservation/variables.tf, autoscaling/alarms/sqs/main.tf, autoscaling/alarms/sqs/sqs_alarm/main.tf, autoscaling/alarms/sqs/sqs_alarm/variables.tf, autoscaling/alarms/sqs/variables.tf, ecs/cluster/asg_ondemand.tf, ecs/cluster/asg_spot.tf, ecs/cluster/variables.tf, sqs_autoscaling_service/main.tf, sqs_autoscaling_service/variables.tf
* Make scale up and down period for an `sqs_autoscaling_service` be configurable
* Fix a bug in the way the cloudwatch metrics alarm are defined which caused them to scale down (or up) before the scaledown period had passed
* Refernce directly the autoscaling modules in the ecs cluster instead of using git ref so that the code from a certain release can be used throughout
=> Autoscaling bugfixes and tweaks

RELEASE.md, ecs/service/ecs_service/ecs.tf, ecs/service/ecs_service/variables.tf, ecs/service/main.tf, ecs/service/variables.tf
Adds the ability to run compute from AWS Fargate for an ECS service.
=> Add Fargate launch type

RELEASE.md, ecs/service/main.tf
This change adds an `APP_NAME` environment variable to the task definition of tasks created with the `ecs` module. The `APP_NAME` variable is set to the value of the container uri used as the primary container in the service.
=> Add container uri as APP_NAME env var in ecs service module

RELEASE.md, autoscaling/app/ecs/main.tf, ecs/modules/service/prebuilt/sqs_scaling/main.tf, ecs/modules/service/prebuilt/sqs_scaling/variables.tf, ecs/modules/task/modules/container_definition/container_with_sidecar/main.tf, ecs/modules/task/modules/container_definition/container_with_sidecar/variables.tf, ecs/modules/task/modules/container_definition/single_container/main.tf, ecs/modules/task/modules/container_definition/single_container/variables.tf, ecs/modules/task/modules/env_vars/main.tf, ecs/modules/task/modules/env_vars/variables.tf, ecs/modules/task/prebuilt/container_with_sidecar+ebs+efs/main.tf, ecs/modules/task/prebuilt/container_with_sidecar+ebs+efs/variables.tf, ecs/modules/task/prebuilt/container_with_sidecar+ebs/main.tf, ecs/modules/task/prebuilt/container_with_sidecar+ebs/variables.tf, ecs/modules/task/prebuilt/container_with_sidecar+efs/main.tf, ecs/modules/task/prebuilt/container_with_sidecar+efs/variables.tf, ecs/modules/task/prebuilt/container_with_sidecar/main.tf, ecs/modules/task/prebuilt/container_with_sidecar/variables.tf, ecs/modules/task/prebuilt/single_container+ebs+efs/main.tf, ecs/modules/task/prebuilt/single_container+ebs+efs/variables.tf, ecs/modules/task/prebuilt/single_container+ebs/main.tf, ecs/modules/task/prebuilt/single_container+ebs/variables.tf, ecs/modules/task/prebuilt/single_container+efs/main.tf, ecs/modules/task/prebuilt/single_container+efs/variables.tf, ecs/modules/task/prebuilt/single_container/main.tf, ecs/modules/task/prebuilt/single_container/variables.tf
According to https://github.com/hashicorp/terraform/issues/17287 and https://github.com/hashicorp/terraform/issues/14677 length can only be calculated for not computed values. If a map or list contains computed values, the whole map is considered as computed. 
This means the way we pass environment variables at the moment only works if there are no computed values (i.e. outputs from modules or outputs from terraform resource types).
So, reintroducing env_vars_length until terraform fixes this
=> Reintroduce env_vars_length

RELEASE.md, efs/main.tf, efs/variables.tf, network/outputs.tf
This introduces new variables to pass on to the EFS modules, so that the number of mount targets to create is not derived from a computed value which might not yet be available. This is a possible workaround to issue #83 and is being used in https://github.com/wellcometrust/workflow/tree/new-infra
=> Introduces new variables to pass on to the EFS modules

RELEASE.md, lambda/outputs.tf
Adding `invoke_arn` attribute of `aws_lambda_function` resource to the outputs of the `lambda` module. This is to enable easy integration of API Gateway which requires this particular ARN for invocation.
=> Lambda module gains `invoke_arn` output

RELEASE.md, ecs/modules/task/modules/iam_roles/main.tf, ecs/modules/task/modules/iam_roles/outputs.tf
It seems in the most recent versions of terraform have caused plans to start failing as the data block refers to resources that do not yet exist. 
This removes the indirect reference and seems to resolve the issue.
=> Remove reference to data element, when resource will do

RELEASE.md, network/prebuilt/vpc/public-private-igw/main.tf, network/prebuilt/vpc/public-private-igw/variables.tf
Set default for prebuilt VPC module enable_dns_hostnames to true
In order that service discovery works as expected
=> Default DNS hostnames

RELEASE.md, ecs/modules/ec2/prebuilt/ebs+efs/variables.tf, ecs/modules/ec2/prebuilt/ebs/variables.tf, ecs/modules/ec2/prebuilt/efs/variables.tf, ecs/modules/ec2/prebuilt/nvm/variables.tf, ecs/modules/ec2/prebuilt/ondemand/variables.tf, ecs/modules/ec2/prebuilt/spot/variables.tf
I don’t think we want it all the time – in some cases (e.g. Loris), we don’t allow SSH access to the instances, so specifying a key is pointless.
=> Allow omitting the SSH key name in the prebuilt EC2 modules

RELEASE.md, _scripts/validate_interfaces.py, ecs/prebuilt/scaling+nvm/main.tf, ecs/prebuilt/scaling+nvm/variables.tf
Because the module it references doesn't take a `vpc_id` parameter any more.
Plus a ropey script for making that sort of thing easier to spot.
=> Fix the worker+nvm module

RELEASE.md, ecs/modules/service/prebuilt/scaling/ecs/main.tf, ecs/modules/service/prebuilt/scaling/ecs/outputs.tf, ecs/modules/service/prebuilt/scaling/ecs/variables.tf, ecs/modules/service/prebuilt/scaling/main.tf
Ignore changes to desired task counts in the scaling ecs module in order that TF applies don't mess with task counts.
=> Ignore desired count changes

RELEASE.md, sns/cross_account_topic_policy.tf, sns/variables.tf
As out topics are spread between accounts (currently `catalogue` and `platform`) this becomes useful to allow other accounts to hook onto these topics, namely, `reporting`.
Because it affects more than 1 repo, it felt like generalising was better than copy / pasting into both repos.
Even if we start being more idealistic and putting these topics in their right repos and accounts, this will probably be needed.
The implementation is non-breaking.
=> add cross account access to SNS topics

RELEASE.md, iam/modules/assumable_role/aws/main.tf, iam/modules/assumable_role/aws/variables.tf, iam/modules/assumable_role/federated/main.tf, iam/modules/assumable_role/federated/variables.tf, iam/prebuilt/account/aws/main.tf, iam/prebuilt/account/aws/variables.tf
In order that sessions don't time out after an hour.
=> Allow max session duration for assumable roles to be variable
