wellcometrust/terraform-modules

ecs_alb/outputs.tf

output the ecs_alb_id

---

rds/security_group.tf
rds/variables.tf

Allows database access security groups to be a list.

RDS allowed security groups

---

autoscaling/app/ecs/locals.tf
autoscaling/app/ecs/main.tf
autoscaling/app/ecs/variables.tf

As per review comments on https://github.com/wellcometrust/terraform/pull/11

Cleans up autoscaling modules

---

sns/outputs.tf

As this can be looked up using the correct terraform data source.
See: https://www.terraform.io/docs/providers/aws/d/sns_topic.html

Remove redundant ARN from SNS module.

---

ecs/cluster/alb/main.tf
ecs/cluster/asg_ondemand.tf

Fixes from working on https://github.com/wellcometrust/platform/pull/1263

Bugfixes for the cluster module

---

RELEASE.md
sqs/sqs.tf
sqs/variables.tf

Plus a light refactoring.
Not tested yet.

Add parameters for SQS queue behaviour in the queue module

---

RELEASE.md
ecs/service/main.tf

Hangover from a small refactor of the last release.

remove use_task_definition_template_path

---

RELEASE.md
ecs/service/ecs_task/cloudwatch.tf
ecs/service/ecs_task/variables.tf
ecs/service/main.tf
ecs/service/variables.tf
ecs_script_task/cloudwatch.tf
ecs_script_task/variables.tf
lambda/cloudwatch_log_group.tf
lambda/variables.tf
sqs_autoscaling_service/main.tf
sqs_autoscaling_service/variables.tf
userdata/cloudwatch.tf
userdata/variables.tf

Useful (required?) for https://github.com/wellcometrust/platform/issues/1731

Add the ability to configure log retention in our modules

---

ec2/asg/cloudformation/asg.json.template
ec2/asg/cloudformation/asg.tf
ec2/asg/main.tf

In order to better identify ASGs and their instances

Add name tag to Autoscaling Group module

---

RELEASE.md
dlami_asg/README.md
dlami_asg/main.tf
dlami_asg/outputs.tf
dlami_asg/userdata.sh.tpl
dlami_asg/variables.tf

This module provides an autoscaling group provisioned by default running instances based on the Amazon Deep Learning AMI.
We add some userdata which installs some useful modules and starts jupyter-notebook server.
This module requires an S3 bucket used by the [s3contents](https://github.com/danielfrg/s3contents) module in which to store notebooks.
An example terraform implementation:
```tf
module "p2_compute" {
source = "git::https://github.com/wellcometrust/terraform-modules.git//ec2/asg?ref=v9.4.0"
name   = "jupyter-p2"
key_name    = "${var.key_name}"
bucket_name = "${aws_s3_bucket.jupyter.id}"
instance_type = "p2.xlarge"
vpc_id      = "${module.vpc.vpc_id}"
vpc_subnets = "${module.vpc.subnets}"
}
resource "aws_s3_bucket" "jupyter" {
bucket = "my_bucket"
acl    = "private" …
```

Data science infrastructure module

---

RELEASE.md
ecs/modules/task/modules/container_definition/single_container/task_definition.json.template
ecs/modules/task/modules/port_mappings/main.tf
ecs/modules/task/prebuilt/container_with_sidecar+ebs+efs/main.tf
ecs/modules/task/prebuilt/container_with_sidecar+ebs/main.tf
ecs/modules/task/prebuilt/container_with_sidecar+efs/main.tf
ecs/modules/task/prebuilt/container_with_sidecar/main.tf

This changes the port mappings module to always specify the host port.

Fix port mappings issue where task definition is recreated constantly

---

RELEASE.md
ec2/modules/instance_profile/main.tf
ecs/modules/ec2/modules/instance_role_policy/main.tf

Causing toggling of policy rules.

Fix instance profile name

---

RELEASE.md
iam/client_bucket_user/user.tf
iam/client_bucket_user/variables.tf

In order to remove keybase restriction.

Allow optional PGP key (not keybase) for client_bucket_user

---

RELEASE.md
rds/main.tf

Set publicly_accessible to false for RDS

Set rds publicly_accessible to false

---

RELEASE.md
ecs/example/prebuilt/main.tf
ecs/example/prebuilt/network.tf
ecs/example/prebuilt/public_loadbalancer.tf
ecs/prebuilt/rest/container_with_sidecar/main.tf
ecs/prebuilt/rest/container_with_sidecar/variables.tf
ecs/prebuilt/rest/single_container/main.tf
ecs/prebuilt/rest/single_container/variables.tf

Fix the ECS example and add a task_count variable

Update ECS modules

---

RELEASE.md
ecs/prebuilt/rest/container_with_sidecar/main.tf
ecs/prebuilt/rest/container_with_sidecar/variables.tf
ecs/prebuilt/rest/single_container/main.tf
ecs/prebuilt/rest/single_container/variables.tf

As the data block doesn't respect dependencies!

 Prevent failed stack creation in ECS modules

---

RELEASE.md
kms/README.md
kms/modules/key/encryption_kms_key.tf
kms/modules/key/iam_policy_document.tf
kms/modules/key/outputs.tf
kms/modules/key/variables.tf

This module is used in the storage service.

Adds kms/key module

---

RELEASE.md
kms/modules/key/encryption_kms_key.tf
vhs/README.md
vhs/modules/dynamo/iam_policy_document.tf
vhs/modules/dynamo/main.tf
vhs/modules/dynamo/outputs.tf
vhs/modules/dynamo/variables.tf
vhs/modules/example/modules/main.tf
vhs/modules/vhs/iam_policy_document.tf
vhs/modules/vhs/main.tf
vhs/modules/vhs/outputs.tf
vhs/modules/vhs/variables.tf

For use with the hybrid store (library https://github.com/wellcometrust/scala-storage)

Adds a VHS module

---

RELEASE.md
network/prebuilt/vpc/public-private-igw/gateway_endpoint/main.tf
network/prebuilt/vpc/public-private-igw/vpc_endpoints.tf

VPC GW endpoint route added to route table

Route VPC Gateway endpoints

---

RELEASE.md
_scripts/check_for_unused_variables.py
ecs/modules/task/modules/container_definition/container_with_sidecar/main.tf
ecs/modules/task/modules/container_definition/container_with_sidecar/variables.tf
ecs/modules/task/modules/iam_roles/outputs.tf
ecs/modules/task/modules/secrets/iam.tf
ecs/modules/task/modules/secrets/main.tf
ecs/modules/task/modules/secrets/variables.tf
ecs/modules/task/modules/task_definition/default/outputs.tf
ecs/modules/task/modules/task_definition/ebs+efs/outputs.tf
ecs/modules/task/modules/task_definition/ebs/outputs.tf
ecs/modules/task/modules/task_definition/efs/outputs.tf
ecs/modules/task/modules/task_definition/nvm/outputs.tf
ecs/modules/task/prebuilt/container_with_sidecar/main.tf
ecs/modules/task/prebuilt/container_with_sidecar/outputs.tf

Required for https://github.com/wellcometrust/platform/pull/3371

All the work to support config/secrets from SSM and KMS

---

RELEASE.md
autoscaling/alarms/queue/main.tf
autoscaling/alarms/queue/variables.tf
ecs/prebuilt/scaling/main.tf
ecs/prebuilt/scaling/variables.tf

Remove custom scaling
Add scaling alarm for queue length

Scaling improvements

---

RELEASE.md
ecs/modules/task/modules/container_definition/container_with_sidecar/main.tf
ecs/modules/task/modules/container_definition/container_with_sidecar/task_definition.json.template
ecs/modules/task/modules/container_definition/container_with_sidecar/variables.tf
ecs/modules/task/modules/container_definition/single_container/main.tf
ecs/modules/task/modules/container_definition/single_container/task_definition.json.template
ecs/modules/task/modules/container_definition/single_container/variables.tf

This lets us ditch the forked modules in the archivematica-infra repo.

Slightly improve the ECS modules

---

RELEASE.md
ecs/modules/task/modules/task_definition/ebs+efs/outputs.tf
ecs/modules/task/modules/task_definition/ebs/outputs.tf
ecs/modules/task/modules/task_definition/efs/outputs.tf
ecs/modules/task/modules/task_definition/nvm/outputs.tf
ecs/modules/task/prebuilt/container_with_sidecar+ebs+efs/outputs.tf
ecs/modules/task/prebuilt/container_with_sidecar+ebs/outputs.tf
ecs/modules/task/prebuilt/container_with_sidecar+efs/outputs.tf
ecs/modules/task/prebuilt/container_with_sidecar/outputs.tf
ecs/modules/task/prebuilt/single_container+ebs+efs/outputs.tf
ecs/modules/task/prebuilt/single_container+ebs/outputs.tf
ecs/modules/task/prebuilt/single_container+efs/outputs.tf
ecs/modules/task/prebuilt/single_container+nvm/outputs.tf
ecs/modules/task/prebuilt/single_container/outputs.tf
ecs/prebuilt/scaling+nvm/outputs.tf
ecs/prebuilt/scaling/outputs.tf

To clean up a bit of weirdness in the storage-service. For wellcometrust/platform#3602.

Export task role ARN from the ECS scaling module

---

RELEASE.md
sqs/queue_policy.tf
sqs/subscription.tf
sqs/variables.tf

To allow cross account subscription

Use topic arns in the sqs module
